In [2]:
import numpy as np
import pandas as pd

In [39]:
#load csv data
data = pd.read_csv("Employee-attrition.csv")
#print(data)
print(data.columns)

Index(['EmployeeID', 'recorddate_key', 'birthdate_key', 'orighiredate_key',
       'terminationdate_key', 'age', 'length_of_service', 'city_name',
       'department_name', 'job_title', 'store_name', 'gender_short',
       'gender_full', 'termreason_desc', 'termtype_desc', 'STATUS_YEAR',
       'STATUS', 'BUSINESS_UNIT'],
      dtype='object')


In [8]:
#Print top 10
print(data.head(10))

   EmployeeID   recorddate_key birthdate_key orighiredate_key  \
0        1318  12/31/2006 0:00      1/3/1954        8/28/1989   
1        1318  12/31/2007 0:00      1/3/1954        8/28/1989   
2        1318  12/31/2008 0:00      1/3/1954        8/28/1989   
3        1318  12/31/2009 0:00      1/3/1954        8/28/1989   
4        1318  12/31/2010 0:00      1/3/1954        8/28/1989   
5        1318  12/31/2011 0:00      1/3/1954        8/28/1989   
6        1318  12/31/2012 0:00      1/3/1954        8/28/1989   
7        1318  12/31/2013 0:00      1/3/1954        8/28/1989   
8        1318  12/31/2014 0:00      1/3/1954        8/28/1989   
9        1318  12/31/2015 0:00      1/3/1954        8/28/1989   

  terminationdate_key  age  length_of_service  city_name department_name  \
0            1/1/1900   52                 17  Vancouver       Executive   
1            1/1/1900   53                 18  Vancouver       Executive   
2            1/1/1900   54                 19  Vancouver

In [9]:
#Print last 5
print(data.tail(5))

       EmployeeID  recorddate_key birthdate_key orighiredate_key  \
49648        8258  12/1/2015 0:00     5/28/1994        8/19/2013   
49649        8264   8/1/2013 0:00     6/13/1994        8/27/2013   
49650        8279  12/1/2015 0:00     7/18/1994        9/15/2013   
49651        8296  12/1/2013 0:00      9/2/1994        10/9/2013   
49652        8321  12/1/2014 0:00    11/28/1994       11/24/2013   

      terminationdate_key  age  length_of_service    city_name  \
49648          12/30/2015   21                  2    Valemount   
49649           8/30/2013   19                  0    Vancouver   
49650          12/30/2015   21                  2   White Rock   
49651          12/31/2013   19                  0      Kelowna   
49652          12/30/2014   20                  1  Grand Forks   

        department_name     job_title  store_name gender_short gender_full  \
49648             Dairy  Dairy Person          34            M        Male   
49649  Customer Service       Cashier 

In [29]:
#Filter Age Data and Describe Data
age_filter = data[(data["age"] > 43) & (data["age"] > 60)]
age_filter.describe()

EmployeeID          age  length_of_service   store_name  STATUS_YEAR
count  3375.000000  3375.000000        3375.000000  3375.000000  3375.000000
mean   2884.511111    62.883259          17.277630    26.393185  2010.974519
std    1208.012452     1.410437           5.696557    12.079210     3.010740
min    1318.000000    61.000000           9.000000     1.000000  2006.000000
25%    1792.500000    62.000000          12.000000    17.000000  2008.000000
50%    2400.000000    63.000000          13.000000    30.000000  2011.000000
75%    3977.000000    64.000000          23.000000    35.000000  2014.000000
max    5108.000000    65.000000          26.000000    46.000000  2015.000000

In [13]:
#Dataset Information
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 49653 entries, 0 to 49652
Data columns (total 18 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   EmployeeID           49653 non-null  int64 
 1   recorddate_key       49653 non-null  object
 2   birthdate_key        49653 non-null  object
 3   orighiredate_key     49653 non-null  object
 4   terminationdate_key  49653 non-null  object
 5   age                  49653 non-null  int64 
 6   length_of_service    49653 non-null  int64 
 7   city_name            49653 non-null  object
 8   department_name      49653 non-null  object
 9   job_title            49653 non-null  object
 10  store_name           49653 non-null  int64 
 11  gender_short         49653 non-null  object
 12  gender_full          49653 non-null  object
 13  termreason_desc      49653 non-null  object
 14  termtype_desc        49653 non-null  object
 15  STATUS_YEAR          49653 non-null  int64 
 16  STAT

In [15]:
# Data Set Describe
data.describe()

EmployeeID           age  length_of_service    store_name  \
count  49653.000000  49653.000000       49653.000000  49653.000000   
mean    4859.495740     42.077035          10.434596     27.297605   
std     1826.571142     12.427257           6.325286     13.514134   
min     1318.000000     19.000000           0.000000      1.000000   
25%     3360.000000     31.000000           5.000000     16.000000   
50%     5031.000000     42.000000          10.000000     28.000000   
75%     6335.000000     53.000000          15.000000     42.000000   
max     8336.000000     65.000000          26.000000     46.000000   

        STATUS_YEAR  
count  49653.000000  
mean    2010.612612  
std        2.845577  
min     2006.000000  
25%     2008.000000  
50%     2011.000000  
75%     2013.000000  
max     2015.000000

In [40]:
#Dataset All columns
data.columns

Index(['EmployeeID', 'recorddate_key', 'birthdate_key', 'orighiredate_key',
       'terminationdate_key', 'age', 'length_of_service', 'city_name',
       'department_name', 'job_title', 'store_name', 'gender_short',
       'gender_full', 'termreason_desc', 'termtype_desc', 'STATUS_YEAR',
       'STATUS', 'BUSINESS_UNIT'],
      dtype='object')

In [41]:
#DataSet columns Data Types
data.dtypes

EmployeeID              int64
recorddate_key         object
birthdate_key          object
orighiredate_key       object
terminationdate_key    object
age                     int64
length_of_service       int64
city_name              object
department_name        object
job_title              object
store_name              int64
gender_short           object
gender_full            object
termreason_desc        object
termtype_desc          object
STATUS_YEAR             int64
STATUS                 object
BUSINESS_UNIT          object
dtype: object

In [21]:
#Dataset Data Shape
data.shape

(49653, 18)

In [30]:
data.sample(10)

EmployeeID   recorddate_key birthdate_key orighiredate_key  \
15028        3823  12/31/2014 0:00     5/20/1962        9/20/1996   
13053        3531  12/31/2007 0:00    10/25/1960       11/23/1995   
42908        7157  12/31/2014 0:00    12/12/1985         3/1/2009   
46447        7816  12/31/2014 0:00    11/28/1990       10/14/2011   
37074        6433  12/31/2008 0:00      4/7/1980         3/1/2006   
4054         2113  12/31/2013 0:00      6/4/1953       12/28/1991   
37916        6522  12/31/2009 0:00    12/30/1980        7/20/2006   
45485        7596  12/31/2012 0:00      4/2/1989       11/29/2010   
6059         2430  12/31/2008 0:00     2/27/1955       11/27/1992   
15928        3946  12/31/2015 0:00     1/19/1963        1/27/1997   

      terminationdate_key  age  length_of_service        city_name  \
15028            1/1/1900   52                 18  New Westminster   
13053            1/1/1900   47                 12         Victoria   
42908            1/1/1900   29                  5        Vancouver   
46447            1/1/1900   24                  3  New Westminster   
37074           8/11/2011   28                  2        Vancouver   
4054             1/1/1900   60                 22          Nanaimo   
37916            1/1/1900   29                  3        Vancouver   
45485            1/1/1900   23                  2        Vancouver   
6059             1/1/1900   53                 16  New Westminster   
15928            1/1/1900   52                 18          Kelowna   

       department_name      job_title  store_name gender_short gender_full  \
15028          Produce  Produce Clerk          21            F      Female   
13053           Bakery          Baker          46            F      Female   
42908            Meats    Meat Cutter          44            F      Female   
46447  Processed Foods  Shelf Stocker          21            F      Female   
37074  Processed Foods  Shelf Stocker          43            M        Male   
4054             Meats    Meat Cutter          18            F      Female   
37916  Processed Foods  Shelf Stocker          43            F      Female   
45485           Bakery          Baker          44            M        Male   
6059             Meats    Meat Cutter          21            M        Male   
15928          Produce  Produce Clerk          16            M        Male   

      termreason_desc   termtype_desc  STATUS_YEAR  STATUS BUSINESS_UNIT  
15028  Not Applicable  Not Applicable         2014  ACTIVE        STORES  
13053  Not Applicable  Not Applicable         2007  ACTIVE        STORES  
42908  Not Applicable  Not Applicable         2014  ACTIVE        STORES  
46447  Not Applicable  Not Applicable         2014  ACTIVE        STORES  
37074  Not Applicable  Not Applicable         2008  ACTIVE        STORES  
4054   Not Applicable  Not Applicable         2013  ACTIVE        STORES  
37916  Not Applicable  Not Applicable         2009  ACTIVE        STORES  
45485  Not Applicable  Not Applicable         2012  ACTIVE        STORES  
6059   Not Applicable  Not Applicable         2008  ACTIVE        STORES  
15928  Not Applicable  Not Applicable         2015  ACTIVE        STORES

In [36]:
# Filter Data by the Column Value
data[(data["city_name"]=="Victoria")]

length_of_service    518109
dtype: int64

In [37]:
#Select Data for Specific Columns
data[["age","length_of_service","gender_full"]].sample(10)

age  length_of_service gender_full
7271    53                 16      Female
5486    61                 23        Male
26672   42                 12      Female
37068   32                  6        Male
20209   45                 13      Female
48894   60                  8        Male
4685    62                 23      Female
17374   49                 16      Female
8321    56                 20        Male
7300    52                 15        Male

In [38]:
#Sum of a column
data[["length_of_service"]].sum()

length_of_service    518109
dtype: int64

In [55]:
#Create a function for return the remaining service years return
def get_remaining_service(row):
    retire_age = 75
    service_age = int(row['age'])    
    remaining_service = retire_age - service_age    
   
    return remaining_service

In [52]:
#Create a new data set with columns Age, length_of_service, gender_full 
editdataset = data[["age","length_of_service","gender_full"]].sample(20)
editdataset

age  length_of_service gender_full
35365   29                  3      Female
11319   54                 18      Female
41359   31                  7        Male
26946   38                  8      Female
21248   42                 10      Female
29849   40                 12      Female
46395   22                  1      Female
44502   23                  0        Male
16266   43                  9      Female
30467   41                 12        Male
18073   50                 17        Male
19532   49                 16      Female
20025   40                  8        Male
41511   25                  1        Male
19903   63                 12      Female
15881   49                 15      Female
12292   48                 13        Male
28989   33                  4      Female
32597   30                  2      Female
46094   24                  3        Male

In [56]:
# Create a new column "rem_service_year" and Call the function "get_remaining_service" for the value
editdataset['rem_service_year'] = editdataset.apply(get_remaining_service, axis=1)

#Sort the dataset values
editdataset.sort_values('rem_service_year', ascending=True).head(20)

age  length_of_service gender_full  rem_service_year
19903   63                 12      Female                12
11319   54                 18      Female                21
18073   50                 17        Male                25
19532   49                 16      Female                26
15881   49                 15      Female                26
12292   48                 13        Male                27
16266   43                  9      Female                32
21248   42                 10      Female                33
30467   41                 12        Male                34
29849   40                 12      Female                35
20025   40                  8        Male                35
26946   38                  8      Female                37
28989   33                  4      Female                42
41359   31                  7        Male                44
32597   30                  2      Female                45
35365   29                  3      Female                46
41511   25                  1        Male                50
46094   24                  3        Male                51
44502   23                  0        Male                52
46395   22                  1      Female                53

In [72]:
arr = np.array([1, 2, 3, 4])

print(f'Array Length = {len(arr)}')
print(f'Total Value = {np.sum(arr)}')

# Find Array index with value:
for i in range(len(arr)):
    print(f'Value for index {i} : {arr[i]}')

Array Length = 4
Total Value = 10
Value for index 0 : 1
Value for index 1 : 2
Value for index 2 : 3
Value for index 3 : 4


In [80]:
#Array slicing
slicearr = np.array([1, 2, 3, 4, 5, 6, 7])
print(slicearr[1:5])
print(slicearr[-3:-1])
print(slicearr[2:-1])

[2 3 4 5]
[5 6]
[3 4 5 6]


In [82]:
twodarr = np.array([[3, 2, 4], [5, 0, 1]])

print(np.sort(twodarr))
print(np.sum(twodarr))

[[2 3 4]
 [0 1 5]]
15


In [84]:
filterarr = np.array([41, 42, 43, 44])

print(filterarr > 43)

[False False False  True]
